server:
  port: 9000

spring:
  application:
    name: auth-service

jwt:
  secret: please-change-this-to-a-long-random-secret-string-at-least-256-bits-for-HS256-algorithm   # 仅 dev 用

springdoc:
  swagger-ui:
    path: /swagger-ui.html
