datastax-java-driver {
  basic {
    contact-points = [ "localhost:9042" ]
    request {
      timeout = 5 seconds
      consistency = LOCAL_QUORUM
    }
    load-balancing-policy {
      local-datacenter = datacenter1
    }
  }
}